### ISSUE TITLE
.asoundrc is deleted after shutting down

### ISSUE THREAD

**Issue by MichielBbal** [sensemakersamsterdam/OpenEars#12]
**Describe the bug**
.asoundrc with the audio settings is deleted by the system after shutting down.  

**To Reproduce**
1. Follow the instruction and cp .asoundrc to /home/pi.
2. reboot the pi
3. ls -a and .asoundrc is no longer there

**Expected behavior**
.asoundrc should be in /home/pi after reboot.

**Comment by rbolte** [comment]
@MichielBbal : Does this still occur?

**Comment by MichielBbal** [comment]
does no longer occur, closing the issue
