### ISSUE TITLE
Test results = NOK

### ISSUE THREAD

**Issue by MichielBbal** [sensemakersamsterdam/OpenEars#14]
Just did a test with the new model (32000) and the new classes file.
I have kept silent for almost three minutes and this is the result:

![image](https://user-images.githubusercontent.com/37507786/119275049-32f13080-bc13-11eb-96aa-48cba39d8e96.png)

Please find the new classes file below:
label;new_label;proportion_train_samples;proportion_eval_samples;description;enable
1000;0;0.5;0.5; Stilte;1
1001;1;0.6;0.6;"556 gunshots";1
1002;2;5.0;5.0;"Brommer Alarm";1
1003;3;1.0;1.0;Brommer;1
1004;4;4.0;4.0;Claxons;1
1005;5;3.0;3.0;"Dichtklappende autodeuren";1
1006;6;0.8;0.8;"Luide mensen (schreeuwen enz)";1
1007;7;10.0;10.0;Motoren;1
1008;8;1.0;1.0;"Terrasgeluide (stille mensen)";1
1009;9;20.0;20.0;"Versterkte muziek";1

**Comment by MichielBbal** [comment]
Update: today did some more testing. I've used Youtube video's to test the classes (for example claxons, loud people, music etc). However, results were NOK. Not a single prediction was correct. 
I would like to discuss all params (in params.py or otherwise) to see if they are right on my RPi. 
We also must write them down.

**Comment by rbolte** [comment]
I agree with Hugo as well and would  like to join to discuss it "all". It would be great to set a date.

When I'm testing, "silence" is not OK. However, brommers, loud people etc. are classified accordingly from Youtube films. Not 100%, but not bad either.

**Comment by MichielBbal** [comment]
@Rob, see first post. I've added Class 1000 Stilte to the existing .csv. 

Update: I am still learning by doing. I've seen there is a variable 'sample_rate' in capture_mqtt.py and I've added it to the mqtt message (as metadata). The sample rate = 16000 and this is the correct value. 

Unfortunately, this makes it all the more harder to find the root cause. ;-)

**Comment by rbolte** [comment]
@MichielBbal  I understood the first post. However, it seems column 2 `new_label` has been renumbered, at least compared to my `classes.csv`. I do not know whether it affects the classification / prediction postprocessing or not.... But I get different results...

**Comment by MichielBbal** [comment]
@rbolte i would love to see your settings. Not only classes.csv but also .asoundrc and other files such as params.py. Is there a way we could share them? (i don't think new_label is used in any of the scripts, though)

**Comment by rbolte** [comment]
@MichielBbal Let's discuss with Hugo. I dived into this issue. Changed my classes.csv as you mentioned in the first post of this issue. Now I get issue 15 too. Only incorrect results and errors now... (Tested with Brommer movies on Youtube that I used before). We need to walk this through with Hugo, also because there seem to be more sound labels than in classes.csv.

I also measured the bytes coming in when setting the capture time to 10 secs. 480000. Expected was 2 bytes * 16.000 samples * 10 secs = 320.000. But my expectations could be wrong... I guess we need Gijs on this one 

And of course you can get my settings (although they are all pretty standard).

**Comment by rbolte** [comment]
OK:
- Sample rate has been dived into with Michiel and Gijs. 16KHz measured from UMIK into Audiodevice. No problem no more.
- Wrong nr of classes in Michiels classes.csv to be solved by Hugo. This is Issue#15

What remains open is the issue originally raised by Michiel: "Not a single prediction was correct". For this we need to discuss with Hugo. This seems to go together with issue 15 as I get correct predictions sometimes. Let's schedule a Skype call...

**Comment by MichielBbal** [comment]
Results accepted. Let's close this issue.
