### ISSUE TITLE
Error 5 juli

### ISSUE THREAD

**Issue by MichielBbal** [sensemakersamsterdam/OpenEars#17]
capture.py en capture_mqtt.py geven (vandaag) de volgende foutmelding:
[INFO] 2021-07-05 19:37:36,051: Start recording.
Traceback (most recent call last):
  File "capture_mqtt.py", line 118, in <module>
    c.start()
  File "capture_mqtt.py", line 69, in start
    self._process_loop()
  File "capture_mqtt.py", line 75, in _process_loop
    with WavProcessor() as proc:
  File "/home/pi/git/OpenEars/devicehive-dev/audio/processor.py", line 47, in __init__
    self._init_vggish()
  File "/home/pi/git/OpenEars/devicehive-dev/audio/processor.py", line 69, in _init_vggish
    vggish.model.load_vggish_slim_checkpoint(sess, params.VGGISH_MODEL)
  File "/home/pi/git/OpenEars/devicehive-dev/audio/utils/vggish/model.py", line 132, in load_vggish_slim_checkpoint
    saver.restore(session, checkpoint_path)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1276, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/training/checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: models/vggish; No such file or directory
pi@raspberrypi:~/git/OpenEars/devicehive-dev $

**Comment by gmos** [comment]
Er is een settings file.  Ik denk settings.py of zo. Kan je die attachen.   En dan in device-hive een ls -R draaien en ook bijvoegen.

**Comment by MichielBbal** [comment]
> Er is een settings file. Ik denk settings.py of zo. Kan je die attachen. En dan in device-hive een ls -R draaien en ook bijvoegen.

pi@raspberrypi:~/git/OpenEars/devicehive-dev $ ls -R
.:
11k16bitpcm.wav  daemon.py      models         rm-monitorhook-log.sh
audio            eval_dir.py    models.zip     samples
capture_mqtt.py  LICENSE        parse_file.py
capture.py       log_config.py  __pycache__

./audio:
alsadevice.py  device.py    params.py     __pycache__
captor.py      __init__.py  processor.py  utils

./audio/__pycache__:
alsadevice.cpython-37.pyc  __init__.cpython-37.pyc  processor.cpython-37.pyc
captor.cpython-37.pyc      params.cpython-37.pyc

./audio/utils:
__init__.py  __pycache__  vggish  youtube8m

./audio/utils/__pycache__:
__init__.cpython-37.pyc

./audio/utils/vggish:
__init__.py  input.py  mel_features.py  model.py  __pycache__

./audio/utils/vggish/__pycache__:
__init__.cpython-37.pyc  mel_features.cpython-37.pyc
input.cpython-37.pyc     model.cpython-37.pyc

./audio/utils/youtube8m:
__init__.py  input.py  model.py  __pycache__

./audio/utils/youtube8m/__pycache__:
__init__.cpython-37.pyc  input.cpython-37.pyc  model.cpython-37.pyc

./models:
old_models  serval03-10-lstm  serval04-20-lstm  serval04-21-lstm  vvgish

./models/old_models:
01_input_selected_classes.csv         model.ckpt-32000.data-00000-of-00001
checkpoint                            model.ckpt-32000.index
classes.csv                           model.ckpt-32000.meta
class_labels_indices_amsterdam2.csv   model.ckpt-9970.data-00000-of-00001
model.ckpt-13810.data-00000-of-00001  model.ckpt-9970.index
model.ckpt-13810.index                model.ckpt-9970.meta
model.ckpt-13810.meta

./models/serval03-10-lstm:
04_input_selected_classes.csv         model.ckpt-32000.index
model.ckpt-32000.data-00000-of-00001  model.ckpt-32000.meta

./models/serval04-20-lstm:
04_input_selected_classes.csv         model.ckpt-26200.index
model.ckpt-26200.data-00000-of-00001  model.ckpt-26200.meta

./models/serval04-21-lstm:
04_input_selected_classes.csv         model.ckpt-32000.index
model.ckpt-32000.data-00000-of-00001  model.ckpt-32000.meta

./models/vvgish:
vggish_model.ckpt  vggish_pca_params.npz

./__pycache__:
log_config.cpython-37.pyc

./samples:
dump-of-wave-files.txt

En params.py staat hier in de github.

**Comment by gmos** [comment]
Er kloppen pathnamen niet:


  *   De vggish directory in models heet vvgish.  Dat is fout.  Rename naar  vggish
  *   In de audio/params.py staan een aantal padnamen fout.  Alle  vvgish omzetten naar vggish
  *   Idem in dezelfde file staat er tegens een / voor vggish.  Die / moet eraf.

Daarna werkt het model met python parse_file.py

**Comment by MichielBbal** [comment]
Dank Gijs!  Dit was de oplossing. 
Het werkt nu en ik heb de sensor in mijn tuin hangen. 
De data wordt succesvol opgestuurd naar de MQTT broker.
Ik sluit het issue.

**Comment by gmos** [comment]
Maar misschien wel ff een change van maken op master, committen, pushen en pull request naar Sensing Clues.
