### ISSUE TITLE
Log: uitval RPi op 26/7 18:09 uur (socket.gaierror:)

### ISSUE THREAD

**Issue by MichielBbal** [sensemakersamsterdam/OpenEars#21]
python stacktrace wordt weggeschreven naar nohup.out.
Hieronder laatste stuk gekopieerd:

[INFO] 2021-07-26 18:08:28,605: Start processing.
[INFO] 2021-07-26 18:08:30,535: Predictions: 
serval:1627315710535: Brommer: 0.99
serval:1627315710535: Claxons: 0.22
serval:1627315710535: Luide mensen (schreeuwen enz): 0.15
serval:1627315710535: Dichtklappende autodeuren: 0.14
serval:1627315710535: Versterkte muziek: 0.14
serval:1627315710535: Motoren: 0.13
serval:1627315710535: Terrasgeluide (stille mensen): 0.11
[INFO] 2021-07-26 18:08:30,555: Stop processing.
[INFO] 2021-07-26 18:08:43,640: Start processing.
[INFO] 2021-07-26 18:08:45,540: Predictions: 
serval:1627315725540: Brommer: 0.99
serval:1627315725540: Claxons: 0.22
serval:1627315725540: Luide mensen (schreeuwen enz): 0.17
serval:1627315725540: Dichtklappende autodeuren: 0.15
serval:1627315725540: Versterkte muziek: 0.14
serval:1627315725540: Terrasgeluide (stille mensen): 0.12
[INFO] 2021-07-26 18:08:45,554: Stop processing.
[INFO] 2021-07-26 18:08:58,688: Start processing.
[INFO] 2021-07-26 18:09:00,604: Predictions: 
serval:1627315740604: Brommer: 0.99
serval:1627315740604: Claxons: 0.21
serval:1627315740604: Luide mensen (schreeuwen enz): 0.16
serval:1627315740604: Dichtklappende autodeuren: 0.15
serval:1627315740604: Versterkte muziek: 0.14
serval:1627315740604: Motoren: 0.13
serval:1627315740604: Terrasgeluide (stille mensen): 0.11
[INFO] 2021-07-26 18:09:00,625: Stop processing.
[INFO] 2021-07-26 18:09:13,725: Start processing.
[INFO] 2021-07-26 18:09:15,636: Predictions: 
serval:1627315755637: Brommer: 0.99
serval:1627315755637: Claxons: 0.22
serval:1627315755637: Luide mensen (schreeuwen enz): 0.15
serval:1627315755637: Motoren: 0.14
serval:1627315755637: Versterkte muziek: 0.14
serval:1627315755637: Dichtklappende autodeuren: 0.14
serval:1627315755637: Terrasgeluide (stille mensen): 0.12

{'Brommer': 0.99442058801651, 'Claxons': 0.21147018671035767, 'Dichtklappende autodeuren': 0.14342167973518372, 'Versterkte muziek': 0.14137312769889832, 'Luide mensen (schreeuwen enz)': 0.1370694488286972, 'Motoren': 0.11352305859327316, 'Terrasgeluide (stille mensen)': 0.11188767850399017, 'cpu_temp': '68.1'}
{'Brommer': 0.9225694537162781, 'Motoren': 0.2831707298755646, 'Versterkte muziek': 0.16477692127227783, 'Terrasgeluide (stille mensen)': 0.14581851661205292, 'Claxons': 0.10847213119268417, 'Dichtklappende autodeuren': 0.10762502998113632, 'cpu_temp': '68.1'}
{'Brommer': 0.9559351801872253, 'Motoren': 0.32427752017974854, 'Versterkte muziek': 0.12948866188526154, 'Claxons': 0.1177886575460434, 'Dichtklappende autodeuren': 0.11426623910665512, 'Terrasgeluide (stille mensen)': 0.10842350125312805, 'cpu_temp': '68.1'}
{'Brommer': 0.9635670185089111, 'Motoren': 0.2782057225704193, 'Claxons': 0.15391094982624054, 'Versterkte muziek': 0.15299001336097717, 'Terrasgeluide (stille mensen)': 0.1344565749168396, 'Dichtklappende autodeuren': 0.11287830770015717, 'cpu_temp': '68.1'}
{'Brommer': 0.988104522228241, 'Claxons': 0.17024533450603485, 'Motoren': 0.16437314450740814, 'Versterkte muziek': 0.1508486121892929, 'Dichtklappende autodeuren': 0.14347729086875916, 'Luide mensen (schreeuwen enz)': 0.13037030398845673, 'Terrasgeluide (stille mensen)': 0.11012178659439087, 'cpu_temp': '68.1'}
{'Brommer': 0.9959761500358582, 'Motoren': 0.14254452288150787, 'Claxons': 0.14095108211040497, 'Dichtklappende autodeuren': 0.14074550569057465, 'cpu_temp': '68.1'}
{'Brommer': 0.9944428205490112, 'Claxons': 0.1742686629295349, 'Dichtklappende autodeuren': 0.15099015831947327, 'Luide mensen (schreeuwen enz)': 0.1464765965938568, 'Versterkte muziek': 0.14281503856182098, 'Motoren': 0.13005153834819794, 'Terrasgeluide (stille mensen)': 0.10841348022222519, 'cpu_temp': '68.1'}
{'Brommer': 0.9946792125701904, 'Claxons': 0.2202390432357788, 'Luide mensen (schreeuwen enz)': 0.170447438955307, 'Dichtklappende autodeuren': 0.15596850216388702, 'Versterkte muziek': 0.13469663262367249, 'Terrasgeluide (stille mensen)': 0.1153758317232132, 'cpu_temp': '68.1'}
{'Brommer': 0.9903712868690491, 'Claxons': 0.22026005387306213, 'Luide mensen (schreeuwen enz)': 0.14957158267498016, 'Dichtklappende autodeuren': 0.13735388219356537, 'Versterkte muziek': 0.13695435225963593, 'Motoren': 0.1348998248577118, 'Terrasgeluide (stille mensen)': 0.11488547921180725, 'cpu_temp': '68.1'}
{'Brommer': 0.9939353466033936, 'Claxons': 0.22037248313426971, 'Luide mensen (schreeuwen enz)': 0.16617979109287262, 'Dichtklappende autodeuren': 0.15386228263378143, 'Versterkte muziek': 0.14034464955329895, 'Terrasgeluide (stille mensen)': 0.11725342273712158, 'cpu_temp': '68.1'}
{'Brommer': 0.9927622079849243, 'Claxons': 0.20533615350723267, 'Luide mensen (schreeuwen enz)': 0.15946637094020844, 'Dichtklappende autodeuren': 0.1478371024131775, 'Versterkte muziek': 0.1395922750234604, 'Motoren': 0.13292181491851807, 'Terrasgeluide (stille mensen)': 0.1131688803434372, 'cpu_temp': '68.1'}
Traceback (most recent call last):
  File "capture_mqtt.py", line 122, in <module>
    c.start()
  File "capture_mqtt.py", line 72, in start
    self._process_loop()
  File "capture_mqtt.py", line 111, in _process_loop
    "pipeline/openears/OE001", payload=msg_str, hostname=mqtt_host, port=mqtt_port, auth=auth
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/publish.py", line 232, in single
    protocol, transport, proxy_args)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/publish.py", line 167, in multiple
    client.connect(hostname, port, keepalive)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by MichielBbal** [comment]
Also the error on  25/7 1:48 CEST.

[INFO] 2021-07-25 01:47:40,046: Start processing.
[INFO] 2021-07-25 01:47:41,985: Predictions: 
serval:1627170461986: Brommer: 0.99
serval:1627170461986: Motoren: 0.29
serval:1627170461986: Claxons: 0.21
serval:1627170461986: Dichtklappende autodeuren: 0.17
[INFO] 2021-07-25 01:47:42,001: Stop processing.
[INFO] 2021-07-25 01:47:55,085: Start processing.
[INFO] 2021-07-25 01:47:56,999: Predictions: 
serval:1627170477000: Motoren: 0.84
serval:1627170477000: Brommer: 0.34
serval:1627170477000: Dichtklappende autodeuren: 0.27
serval:1627170477000: Claxons: 0.20
[INFO] 2021-07-25 01:47:57,018: Stop processing.
[INFO] 2021-07-25 01:48:10,131: Start processing.
[INFO] 2021-07-25 01:48:12,055: Predictions: 
serval:1627170492055: Motoren: 0.97
serval:1627170492055: Claxons: 0.91
serval:1627170492055: Dichtklappende autodeuren: 0.12
[INFO] 2021-07-25 01:48:12,075: Stop processing.
[INFO] 2021-07-25 01:48:25,169: Start processing.
[INFO] 2021-07-25 01:48:27,104: Predictions: 
serval:1627170507104: Motoren: 0.81
serval:1627170507104: Brommer: 0.46
serval:1627170507104: Claxons: 0.27
serval:1627170507104: Dichtklappende autodeuren: 0.27

{'Brommer': 0.9947866797447205, 'Claxons': 0.20543864369392395, 'Luide mensen (schreeuwen enz)': 0.17229479551315308, 'Versterkte muziek': 0.15409639477729797, 'Dichtklappende autodeuren': 0.1474248319864273, 'Terrasgeluide (stille mensen)': 0.11835616827011108, 'Motoren': 0.10718534141778946, 'cpu_temp': '58.4'}
{'Brommer': 0.995335042476654, 'Claxons': 0.23795077204704285, 'Luide mensen (schreeuwen enz)': 0.16448916494846344, 'Dichtklappende autodeuren': 0.1494523137807846, 'Versterkte muziek': 0.14738009870052338, 'Terrasgeluide (stille mensen)': 0.1211603581905365, 'cpu_temp': '58.4'}
{'Brommer': 0.9931614398956299, 'Claxons': 0.19686229526996613, 'Dichtklappende autodeuren': 0.14072898030281067, 'Luide mensen (schreeuwen enz)': 0.1375664472579956, 'Versterkte muziek': 0.1347411423921585, 'Motoren': 0.11251600086688995, 'Terrasgeluide (stille mensen)': 0.10730606317520142, 'cpu_temp': '58.4'}
{'Brommer': 0.9949591755867004, 'Claxons': 0.21150584518909454, 'Luide mensen (schreeuwen enz)': 0.14694127440452576, 'Dichtklappende autodeuren': 0.14601702988147736, 'Versterkte muziek': 0.1417701691389084, 'Terrasgeluide (stille mensen)': 0.11604688316583633, 'cpu_temp': '58.4'}
{'Brommer': 0.9960801601409912, 'Claxons': 0.22551530599594116, 'Luide mensen (schreeuwen enz)': 0.17336291074752808, 'Dichtklappende autodeuren': 0.1533409208059311, 'Versterkte muziek': 0.14489281177520752, 'Terrasgeluide (stille mensen)': 0.11818712949752808, 'cpu_temp': '58.4'}
{'Brommer': 0.9957512617111206, 'Claxons': 0.2150118052959442, 'Luide mensen (schreeuwen enz)': 0.1679263412952423, 'Dichtklappende autodeuren': 0.1484362632036209, 'Versterkte muziek': 0.1467977613210678, 'Terrasgeluide (stille mensen)': 0.12190678715705872, 'cpu_temp': '58.4'}
{'Brommer': 0.9953234791755676, 'Claxons': 0.20566770434379578, 'Luide mensen (schreeuwen enz)': 0.1587987244129181, 'Versterkte muziek': 0.14903587102890015, 'Dichtklappende autodeuren': 0.14603883028030396, 'Terrasgeluide (stille mensen)': 0.11703363806009293, 'Motoren': 0.10371914505958557, 'cpu_temp': '58.4'}
{'Brommer': 0.9980006217956543, 'Dichtklappende autodeuren': 0.15879057347774506, 'Claxons': 0.1399453729391098, 'cpu_temp': '58.4'}
{'Motoren': 0.851447582244873, 'Brommer': 0.5908947587013245, 'Dichtklappende autodeuren': 0.31682491302490234, 'Claxons': 0.15232054889202118, 'cpu_temp': '58.4'}
{'Brommer': 0.9228646159172058, 'Claxons': 0.4571547210216522, 'Motoren': 0.42274007201194763, 'Dichtklappende autodeuren': 0.15231770277023315, 'cpu_temp': '58.4'}
{'Claxons': 0.9965156316757202, 'Brommer': 0.32169678807258606, 'Motoren': 0.20181116461753845, 'Dichtklappende autodeuren': 0.1740027517080307, 'cpu_temp': '58.4'}
{'Brommer': 0.993136465549469, 'Motoren': 0.32256585359573364, 'Claxons': 0.16391463577747345, 'Dichtklappende autodeuren': 0.1531311422586441, 'cpu_temp': '58.4'}
{'Brommer': 0.9852915406227112, 'Motoren': 0.2502293288707733, 'Claxons': 0.22777791321277618, 'Dichtklappende autodeuren': 0.17051047086715698, 'cpu_temp': '58.4'}
{'Brommer': 0.7692645192146301, 'Claxons': 0.5532441139221191, 'Motoren': 0.3689112067222595, 'Dichtklappende autodeuren': 0.15679116547107697, 'cpu_temp': '58.4'}
{'Claxons': 0.9943435788154602, 'Motoren': 0.3458465039730072, 'Dichtklappende autodeuren': 0.149449422955513, 'cpu_temp': '58.4'}
{'Motoren': 0.8221341967582703, 'Claxons': 0.5807628631591797, 'Brommer': 0.3110577166080475, 'Dichtklappende autodeuren': 0.1586768627166748, 'cpu_temp': '58.4'}
{'Motoren': 0.9577781558036804, 'Brommer': 0.4476913809776306, 'Terrasgeluide (stille mensen)': 0.22597746551036835, 'Versterkte muziek': 0.11122895777225494, 'cpu_temp': '58.4'}
{'Brommer': 0.9940982460975647, 'Motoren': 0.19084565341472626, 'Claxons': 0.11786209791898727, 'Dichtklappende autodeuren': 0.11379136890172958, 'cpu_temp': '58.4'}
{'Brommer': 0.9959878325462341, 'Motoren': 0.2288530468940735, 'Claxons': 0.21742738783359528, 'Dichtklappende autodeuren': 0.1380399912595749, 'cpu_temp': '58.4'}
{'Brommer': 0.943179190158844, 'Motoren': 0.6619026064872742, 'Dichtklappende autodeuren': 0.2151278257369995, 'Claxons': 0.16343778371810913, 'cpu_temp': '58.4'}
{'Brommer': 0.9900692701339722, 'Motoren': 0.438790887594223, 'Dichtklappende autodeuren': 0.16149067878723145, 'Claxons': 0.13713575899600983, 'cpu_temp': '58.4'}
{'Brommer': 0.9225627779960632, 'Motoren': 0.6147510409355164, 'Claxons': 0.249863862991333, 'Dichtklappende autodeuren': 0.15661349892616272, '556 gunshots': 0.10387308895587921, 'cpu_temp': '58.4'}
{'Brommer': 0.9035127758979797, 'Claxons': 0.5639646053314209, 'Motoren': 0.35263121128082275, 'Dichtklappende autodeuren': 0.14049889147281647, 'cpu_temp': '58.4'}
{'Claxons': 0.9273484349250793, 'Brommer': 0.8867039680480957, 'Motoren': 0.29352056980133057, 'Dichtklappende autodeuren': 0.1407836675643921, 'cpu_temp': '58.4'}
{'Brommer': 0.9913411736488342, 'Motoren': 0.28860175609588623, 'Claxons': 0.21206922829151154, 'Dichtklappende autodeuren': 0.1709543913602829, 'cpu_temp': '58.4'}
{'Motoren': 0.8372356295585632, 'Brommer': 0.33655643463134766, 'Dichtklappende autodeuren': 0.26566988229751587, 'Claxons': 0.19639332592487335, 'cpu_temp': '58.4'}
{'Motoren': 0.968768835067749, 'Claxons': 0.9057220816612244, 'Dichtklappende autodeuren': 0.11679752916097641, 'cpu_temp': '58.4'}
Traceback (most recent call last):
  File "capture_mqtt.py", line 122, in <module>
    c.start()
  File "capture_mqtt.py", line 72, in start
    self._process_loop()
  File "capture_mqtt.py", line 111, in _process_loop
    "pipeline/openears/OE001", payload=msg_str, hostname=mqtt_host, port=mqtt_port, auth=auth
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/publish.py", line 232, in single
    protocol, transport, proxy_args)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/publish.py", line 167, in multiple
    client.connect(hostname, port, keepalive)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by gmos** [comment]
The error is a kickup in the wifi or vpn.  App should not crash.    About here:  capture_mqtt.py", line 111  you would want a
   try:
       do_the_mqtt_call(…)
   except Exception:
        pass

Measurements that cannot be transmitted will be lost, but that’s not a big problem I guess.

**Comment by MichielBbal** [comment]
Thanks Gijs! Will try to find time to do this update later this week.

**Comment by MichielBbal** [comment]
Fixed it with try... except...
Updated the repo and did a git pull on the Pi.
