### ISSUE TITLE
Environment does not contain an activate script.

### ISSUE THREAD

**Issue by hugokoopmans** [sensemakersamsterdam/OpenEars#7]
Hallo,

Ik heb de install scripts gedraait etc etc alles werkte goed, nu zijn we een paar maanden verder en wilde ik eea weer oppakken.

Ik loop tegen het volgende probleem aan:

```
pi@serval-v001:~/OpenEars/serval $ cat todevicehive.sh 
# to run: use source activate.sh
source serval.env
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=~/Envs
source /usr/local/bin/virtualenvwrapper.sh 
workon serval
cd ../devicehive-dev
pi@serval-v001:~/OpenEars/serval $ ./todevicehive.sh 
ERROR: Environment '/home/pi/Envs/serval' does not contain an activate script.
```

Lijkt er op dat ik de virtual environments kwijt ben ofzo?

Ik heb de SD kaart gecloned en dus weer opnieuw opgestart zou daar iets niet persistent zijn veranderd?

(ik heb een nieuw lstm model getrained, die wil ik nu helemaal live zetten inclusief reporting over MQTT)

@gmos jij weet vast wat er aan de hand is nu? 
thx hugo

**Comment by MichielBbal** [comment]
is working now, so time to close the issue.
